import "./globals.css";
import { Provider } from "./providers";
import HomeHeader from "@/components/HomeHeader/HomeHeader";
import styles from "./layout.module.css";
import { BalanceProvider } from "@/utils/context";

export const metadata = {
  title: "Your Horror Films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link 
                    href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" 
                    rel="stylesheet"
                />
            </head>
            <body>
                <Provider>
                    <BalanceProvider>
                        <div className={styles.layoutContainer}>
                            <HomeHeader />
                            <div className={styles.layoutContent}>
                                {children}
                            </div>
                        </div>
                    </BalanceProvider>
                </Provider>
            </body>
        </html>
    );
}
