import "./globals.css";
import { Provider } from "./providers";

export const metadata = {
  title: "Your Horror Films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Provider>
                    {children}
                </Provider>
            </body>
        </html>
    );
}
