import "./globals.css";
import { Provider } from "./providers";
import HomeHeader from "@/components/HomeHeader/HomeHeader";
import styles from "./layout.module.css";

export const metadata = {
  title: "Your Horror Films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Provider>
                    <div className={styles.layoutContainer}>
                        <HomeHeader />
                        <div className={styles.layoutContent}>
                            {children}
                        </div>
                    </div>
                </Provider>
            </body>
        </html>
    );
}
